# Generated by Django 3.0.6 on 2020-12-20 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='theme',
            field=models.CharField(max_length=64),
        ),
    ]
