# Generated by Django 3.1.4 on 2020-12-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_auto_20201220_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
