# Generated by Django 3.0.6 on 2020-12-20 17:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201220_2043'),
        ('plays', '0004_theme_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('play', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Play')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('play', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Play')),
            ],
        ),
    ]
