# Generated by Django 3.1.4 on 2020-12-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poetry_prose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poetry',
            new_name='Poem',
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'verbose_name_plural': 'Plays'},
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'verbose_name_plural': 'Poetry'},
        ),
        migrations.AlterModelOptions(
            name='prose',
            options={'verbose_name_plural': 'Prose'},
        ),
    ]
