# Generated by Django 3.1.4 on 2020-12-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201220_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='playwright',
            field=models.CharField(default='bruh', max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.CharField(default='bruh', max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prose',
            name='author',
            field=models.CharField(default=1, max_length=69),
            preserve_default=False,
        ),
    ]
