# Generated by Django 3.1.4 on 2020-12-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201220_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prose',
            options={'verbose_name_plural': 'Proses'},
        ),
    ]
