# Generated by Django 3.1.4 on 2020-12-21 07:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20201221_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('prose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prose')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('prose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prose')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('prose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prose')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
            },
        ),
    ]
